#!/usr/bin/env bats
# 06-subcommands.bats — end-to-end subcommand tests against fixture images.

IMAGE="${IMAGE:-1121citrus/usb-explore:latest}"
FIXTURES="${BATS_TEST_DIRNAME}/fixtures"

setup() {
    TMPDIR_WORK=$(mktemp -d)
    # SERVE_CID / MOUNT_CID hold IDs of detached containers started by a test;
    # teardown() stops them so the test body never needs trap EXIT (which would
    # replace bats' own EXIT handler and suppress the TAP result line).
    SERVE_CID=""
    MOUNT_CID=""
}

teardown() {
    if [[ -n "${SERVE_CID}" ]]; then
        docker stop "${SERVE_CID}" >/dev/null 2>&1 || true
        SERVE_CID=""
    fi
    if [[ -n "${MOUNT_CID}" ]]; then
        docker stop "${MOUNT_CID}" >/dev/null 2>&1 || true
        MOUNT_CID=""
    fi
    rm -rf "${TMPDIR_WORK}"
}

# Shorthand: run a container subcommand against single-ext4.img
run_single() {
    docker run --rm --privileged \
        -v "${FIXTURES}/single-ext4.img:/disk.img:ro" \
        -e "USB_PARTITION=2" \
        "$@"
}

# ensure_enterprise_fixture — build showcase-enterprise.img on demand.
# The enterprise showcase image (LUKS1 -> LVM, ~50 MB) is intentionally not
# committed; it is generated by test/fixtures/generate.sh the first time a
# test needs it. generate.sh is idempotent and only builds the requested,
# missing image. Returns 0 when the fixture exists afterwards.
ensure_enterprise_fixture() {
    [[ -f "${FIXTURES}/showcase-enterprise.img" ]] && return 0
    command -v docker >/dev/null 2>&1 || return 1
    bash "${FIXTURES}/generate.sh" showcase-enterprise.img >/dev/null 2>&1
    [[ -f "${FIXTURES}/showcase-enterprise.img" ]]
}

# ---------------------------------------------------------------------------
# archive
# ---------------------------------------------------------------------------

@test "subcommand archive: creates .tar.gz from a partition directory" {
    [[ -f "${FIXTURES}/single-ext4.img" ]] || skip "fixture not generated"
    local outdir="${TMPDIR_WORK}/archive-out"
    mkdir -p "${outdir}"

    run docker run --rm --privileged \
        -v "${FIXTURES}/single-ext4.img:/disk.img:ro" \
        -v "${outdir}:/out" \
        -e "USB_PARTITION=2" \
        "${IMAGE}" archive /etc etc.tar.gz

    [ "${status}" -eq 0 ]
    [[ -f "${outdir}/etc.tar.gz" ]]
}

@test "subcommand archive: .tar.gz contains expected files" {
    [[ -f "${FIXTURES}/single-ext4.img" ]] || skip "fixture not generated"
    local outdir="${TMPDIR_WORK}/archive-contents"
    mkdir -p "${outdir}"

    docker run --rm --privileged \
        -v "${FIXTURES}/single-ext4.img:/disk.img:ro" \
        -v "${outdir}:/out" \
        -e "USB_PARTITION=2" \
        "${IMAGE}" archive /etc etc.tar.gz

    run tar -tzf "${outdir}/etc.tar.gz"
    [ "${status}" -eq 0 ]
    [[ "${output}" == *"hostname"* ]]
}

@test "subcommand archive: archives a single file as .tar" {
    [[ -f "${FIXTURES}/single-ext4.img" ]] || skip "fixture not generated"
    local outdir="${TMPDIR_WORK}/archive-single"
    mkdir -p "${outdir}"

    docker run --rm --privileged \
        -v "${FIXTURES}/single-ext4.img:/disk.img:ro" \
        -v "${outdir}:/out" \
        -e "USB_PARTITION=2" \
        "${IMAGE}" archive /etc/hostname hostname.tar

    run tar -xOf "${outdir}/hostname.tar"
    [ "${status}" -eq 0 ]
    [[ "${output}" == *"usb-explore-test"* ]]
}

@test "subcommand archive: exits 1 for non-existent source path" {
    [[ -f "${FIXTURES}/single-ext4.img" ]] || skip "fixture not generated"
    local outdir="${TMPDIR_WORK}/archive-missing"
    mkdir -p "${outdir}"

    run docker run --rm --privileged \
        -v "${FIXTURES}/single-ext4.img:/disk.img:ro" \
        -v "${outdir}:/out" \
        -e "USB_PARTITION=2" \
        "${IMAGE}" archive /does/not/exist missing.tar.gz

    [ "${status}" -ne 0 ]
    [[ "${output}" == *"not found"* ]]
}

# ---------------------------------------------------------------------------
# copy
# ---------------------------------------------------------------------------

@test "subcommand copy: copies /etc/hostname from ext4 partition to host" {
    [[ -f "${FIXTURES}/single-ext4.img" ]] || skip "fixture not generated"
    local outdir="${TMPDIR_WORK}/copy-out"
    mkdir -p "${outdir}"

    run docker run --rm --privileged \
        -v "${FIXTURES}/single-ext4.img:/disk.img:ro" \
        -v "${outdir}:/out" \
        -e "USB_PARTITION=2" \
        "${IMAGE}" copy /etc/hostname hostname

    [ "${status}" -eq 0 ]
    [[ -f "${outdir}/hostname" ]]
    grep -q "usb-explore-test" "${outdir}/hostname"
}

@test "subcommand copy: copies a directory from the partition" {
    [[ -f "${FIXTURES}/single-ext4.img" ]] || skip "fixture not generated"
    local outdir="${TMPDIR_WORK}/copy-etc"
    mkdir -p "${outdir}"

    run docker run --rm --privileged \
        -v "${FIXTURES}/single-ext4.img:/disk.img:ro" \
        -v "${outdir}:/out" \
        -e "USB_PARTITION=2" \
        "${IMAGE}" copy /etc etc

    [ "${status}" -eq 0 ]
    [[ -d "${outdir}/etc" ]]
    [[ -f "${outdir}/etc/hostname" ]]
}

@test "subcommand copy: exits 1 for non-existent source path" {
    [[ -f "${FIXTURES}/single-ext4.img" ]] || skip "fixture not generated"
    local outdir="${TMPDIR_WORK}/copy-missing"
    mkdir -p "${outdir}"

    run docker run --rm --privileged \
        -v "${FIXTURES}/single-ext4.img:/disk.img:ro" \
        -v "${outdir}:/out" \
        -e "USB_PARTITION=2" \
        "${IMAGE}" copy /does/not/exist missing

    [ "${status}" -ne 0 ]
    [[ "${output}" == *"not found"* ]]
}

# ---------------------------------------------------------------------------
# diff
# ---------------------------------------------------------------------------

@test "subcommand diff: identical file returns 0" {
    [[ -f "${FIXTURES}/single-ext4.img" ]] || skip "fixture not generated"
    # Copy the hostname out, then diff it back — should be identical
    local refdir="${TMPDIR_WORK}/ref"
    mkdir -p "${refdir}"

    docker run --rm --privileged \
        -v "${FIXTURES}/single-ext4.img:/disk.img:ro" \
        -v "${refdir}:/out" \
        -e "USB_PARTITION=2" \
        "${IMAGE}" copy /etc/hostname hostname >/dev/null

    run docker run --rm --privileged \
        -v "${FIXTURES}/single-ext4.img:/disk.img:ro" \
        -v "${refdir}:/ref:ro" \
        -e "USB_PARTITION=2" \
        "${IMAGE}" diff /etc/hostname hostname

    [ "${status}" -eq 0 ]
}

@test "subcommand diff: different file returns 1" {
    [[ -f "${FIXTURES}/single-ext4.img" ]] || skip "fixture not generated"
    local refdir="${TMPDIR_WORK}/ref-diff"
    mkdir -p "${refdir}"
    echo "something-different" > "${refdir}/hostname"

    run docker run --rm --privileged \
        -v "${FIXTURES}/single-ext4.img:/disk.img:ro" \
        -v "${refdir}:/ref:ro" \
        -e "USB_PARTITION=2" \
        "${IMAGE}" diff /etc/hostname hostname

    [ "${status}" -eq 1 ]
}

# ---------------------------------------------------------------------------
# dirty-ext4.img (unclean journal — regression test for noload fix)
# ---------------------------------------------------------------------------

@test "subcommand dirty-ext4: mounts and reads file from partition with dirty journal" {
    [[ -f "${FIXTURES}/dirty-ext4.img" ]] || skip "fixture dirty-ext4.img not generated"
    run docker run --rm --privileged \
        -v "${FIXTURES}/dirty-ext4.img:/disk.img:ro" \
        -e "USB_PARTITION=2" \
        "${IMAGE}" run cat /mnt/part/etc/hostname

    [ "${status}" -eq 0 ]
    [[ "${output}" == *"dirty-ext4-test"* ]]
}

# ---------------------------------------------------------------------------
# find
# ---------------------------------------------------------------------------

@test "subcommand find: finds files by name glob" {
    [[ -f "${FIXTURES}/single-ext4.img" ]] || skip "fixture not generated"
    run docker run --rm --privileged \
        -v "${FIXTURES}/single-ext4.img:/disk.img:ro" \
        -e "USB_PARTITION=2" \
        "${IMAGE}" find "hostname"
    [ "${status}" -eq 0 ]
    [[ "${output}" == *"/etc/hostname"* ]]
}

@test "subcommand find: --grep finds file contents" {
    [[ -f "${FIXTURES}/single-ext4.img" ]] || skip "fixture not generated"
    run docker run --rm --privileged \
        -v "${FIXTURES}/single-ext4.img:/disk.img:ro" \
        -e "USB_PARTITION=2" \
        "${IMAGE}" find --grep "usb-explore-test"
    [ "${status}" -eq 0 ]
    [[ "${output}" == *"/etc/hostname"* ]]
    [[ "${output}" == *"usb-explore-test"* ]]
}

@test "subcommand find: combines name glob and --grep" {
    [[ -f "${FIXTURES}/single-ext4.img" ]] || skip "fixture not generated"
    run docker run --rm --privileged \
        -v "${FIXTURES}/single-ext4.img:/disk.img:ro" \
        -e "USB_PARTITION=2" \
        "${IMAGE}" find "hostname" --grep "usb-explore-test"
    [ "${status}" -eq 0 ]
    [[ "${output}" == *"usb-explore-test"* ]]
}

@test "subcommand find: --grep exits 1 when nothing matches" {
    [[ -f "${FIXTURES}/single-ext4.img" ]] || skip "fixture not generated"
    run docker run --rm --privileged \
        -v "${FIXTURES}/single-ext4.img:/disk.img:ro" \
        -e "USB_PARTITION=2" \
        "${IMAGE}" find --grep "ZZZNOMATCHZZZ"
    [ "${status}" -eq 1 ]
}

@test "subcommand find: name search exits 0 when nothing matches" {
    [[ -f "${FIXTURES}/single-ext4.img" ]] || skip "fixture not generated"
    run docker run --rm --privileged \
        -v "${FIXTURES}/single-ext4.img:/disk.img:ro" \
        -e "USB_PARTITION=2" \
        "${IMAGE}" find "ZZZNOMATCH.xyz"
    [ "${status}" -eq 0 ]
}

# ---------------------------------------------------------------------------
# hash
# ---------------------------------------------------------------------------

@test "subcommand hash: prints sha256 checksum of a file" {
    [[ -f "${FIXTURES}/single-ext4.img" ]] || skip "fixture not generated"
    run docker run --rm --privileged \
        -v "${FIXTURES}/single-ext4.img:/disk.img:ro" \
        -e "USB_PARTITION=2" \
        "${IMAGE}" hash /etc/hostname
    [ "${status}" -eq 0 ]
    # SHA-256 digest is 64 lowercase hex characters followed by two spaces
    [[ "${output}" =~ ^[0-9a-f]{64}[[:space:]][[:space:]] ]]
}

@test "subcommand hash: output path is partition-relative (no /mnt/part)" {
    [[ -f "${FIXTURES}/single-ext4.img" ]] || skip "fixture not generated"
    run docker run --rm --privileged \
        -v "${FIXTURES}/single-ext4.img:/disk.img:ro" \
        -e "USB_PARTITION=2" \
        "${IMAGE}" hash /etc/hostname
    [ "${status}" -eq 0 ]
    [[ "${output}" == *"/etc/hostname"* ]]
    [[ "${output}" != *"/mnt/part"* ]]
}

@test "subcommand hash: result matches sha256sum of the extracted file" {
    [[ -f "${FIXTURES}/single-ext4.img" ]] || skip "fixture not generated"
    local outdir="${TMPDIR_WORK}/hash-verify"
    mkdir -p "${outdir}"

    docker run --rm --privileged \
        -v "${FIXTURES}/single-ext4.img:/disk.img:ro" \
        -v "${outdir}:/out" \
        -e "USB_PARTITION=2" \
        "${IMAGE}" copy /etc/hostname hostname >/dev/null

    local img_hash host_hash
    img_hash=$(docker run --rm --privileged \
        -v "${FIXTURES}/single-ext4.img:/disk.img:ro" \
        -e "USB_PARTITION=2" \
        "${IMAGE}" hash /etc/hostname | awk '{print $1}')
    host_hash=$(sha256sum "${outdir}/hostname" | awk '{print $1}')

    [ "${img_hash}" = "${host_hash}" ]
    [ -n "${img_hash}" ]
}

@test "subcommand hash: exits 1 for non-existent path" {
    [[ -f "${FIXTURES}/single-ext4.img" ]] || skip "fixture not generated"
    run docker run --rm --privileged \
        -v "${FIXTURES}/single-ext4.img:/disk.img:ro" \
        -e "USB_PARTITION=2" \
        "${IMAGE}" hash /does/not/exist
    [ "${status}" -eq 1 ]
    [[ "${output}" == *"not found"* ]]
}

@test "subcommand hash: exits 1 for a directory path" {
    [[ -f "${FIXTURES}/single-ext4.img" ]] || skip "fixture not generated"
    run docker run --rm --privileged \
        -v "${FIXTURES}/single-ext4.img:/disk.img:ro" \
        -e "USB_PARTITION=2" \
        "${IMAGE}" hash /etc
    [ "${status}" -eq 1 ]
    [[ "${output}" == *"directory"* ]]
}

# ---------------------------------------------------------------------------
# mbr.img (MBR layout)
# ---------------------------------------------------------------------------

@test "subcommand mbr: can read hostname from MBR ext4 partition 1" {
    [[ -f "${FIXTURES}/mbr.img" ]] || skip "fixture mbr.img not generated"
    run docker run --rm --privileged \
        -v "${FIXTURES}/mbr.img:/disk.img:ro" \
        -e "USB_PARTITION=1" \
        "${IMAGE}" run cat /mnt/part/etc/hostname

    [ "${status}" -eq 0 ]
    [[ "${output}" == *"mbr-test"* ]]
}

# ---------------------------------------------------------------------------
# run
# ---------------------------------------------------------------------------

@test "subcommand run: cat /mnt/part/etc/hostname returns expected content" {
    [[ -f "${FIXTURES}/single-ext4.img" ]] || skip "fixture not generated"
    run docker run --rm --privileged \
        -v "${FIXTURES}/single-ext4.img:/disk.img:ro" \
        -e "USB_PARTITION=2" \
        "${IMAGE}" run cat /mnt/part/etc/hostname

    [ "${status}" -eq 0 ]
    [[ "${output}" == *"usb-explore-test"* ]]
}

@test "subcommand run: find works on /mnt/part" {
    [[ -f "${FIXTURES}/single-ext4.img" ]] || skip "fixture not generated"
    run docker run --rm --privileged \
        -v "${FIXTURES}/single-ext4.img:/disk.img:ro" \
        -e "USB_PARTITION=2" \
        "${IMAGE}" run find /mnt/part/etc -name hostname

    [ "${status}" -eq 0 ]
    [[ "${output}" == *"hostname"* ]]
}

# ---------------------------------------------------------------------------
# serve (HTTP directory server)
# ---------------------------------------------------------------------------

@test "subcommand serve: HTTP server returns directory listing for ext4 partition" {
    [[ -f "${FIXTURES}/single-ext4.img" ]] || skip "fixture not generated"

    local port=19080
    SERVE_CID=$(docker run --rm -d --privileged \
        -v "${FIXTURES}/single-ext4.img:/disk.img:ro" \
        -e "USB_PARTITION=2" \
        -p "${port}:8080" \
        "${IMAGE}" serve)

    # Wait up to 10 s for the HTTP server to respond
    local ready=false
    for _ in $(seq 1 20); do
        sleep 0.5
        if curl -sf "http://localhost:${port}/" >/dev/null 2>&1; then
            ready=true; break
        fi
    done
    [[ "${ready}" == true ]] || skip "HTTP server did not start within 10 s"

    run curl -sf "http://localhost:${port}/"
    [ "${status}" -eq 0 ]
    # Directory listing should contain the 'etc' directory planted in the fixture
    [[ "${output}" == *"etc"* ]]
}

@test "subcommand serve: individual file is retrievable via HTTP" {
    [[ -f "${FIXTURES}/single-ext4.img" ]] || skip "fixture not generated"

    local port=19081
    SERVE_CID=$(docker run --rm -d --privileged \
        -v "${FIXTURES}/single-ext4.img:/disk.img:ro" \
        -e "USB_PARTITION=2" \
        -p "${port}:8080" \
        "${IMAGE}" serve)

    local ready=false
    for _ in $(seq 1 20); do
        sleep 0.5
        if curl -sf "http://localhost:${port}/" >/dev/null 2>&1; then
            ready=true; break
        fi
    done
    [[ "${ready}" == true ]] || skip "HTTP server did not start within 10 s"

    run curl -sf "http://localhost:${port}/etc/hostname"
    [ "${status}" -eq 0 ]
    [[ "${output}" == *"usb-explore-test"* ]]
}

# ---------------------------------------------------------------------------
# shell (non-interactive: run a command and exit)
# ---------------------------------------------------------------------------

@test "subcommand shell: partition is mounted and accessible via run subcommand" {
    # shell is interactive; verify the partition mounts by using 'run' which
    # exercises the same mount_partition path without requiring a tty.
    [[ -f "${FIXTURES}/single-ext4.img" ]] || skip "fixture not generated"
    run docker run --rm --privileged \
        -v "${FIXTURES}/single-ext4.img:/disk.img:ro" \
        -e "USB_PARTITION=2" \
        "${IMAGE}" run ls /mnt/part
    [ "${status}" -eq 0 ]
    [[ "${output}" == *"etc"* ]]
}

# ---------------------------------------------------------------------------
# xfs.img (driver test)
# ---------------------------------------------------------------------------

# ---------------------------------------------------------------------------
# squashfs.img (driver test)
# ---------------------------------------------------------------------------

@test "subcommand squashfs: squashfs partition is identified by info --json" {
    [[ -f "${FIXTURES}/squashfs.img" ]] || skip "fixture squashfs.img not generated"
    local fstype
    fstype=$(docker run --rm --privileged \
        -v "${FIXTURES}/squashfs.img:/disk.img:ro" \
        "${IMAGE}" info --json | \
        docker run --rm -i --entrypoint=jq \
            "${IMAGE}" -r '.partitions[] | select(.number == 2) | .fstype')
    [ "${fstype}" = "squashfs" ]
}

@test "subcommand squashfs: can read hostname from squashfs partition" {
    [[ -f "${FIXTURES}/squashfs.img" ]] || skip "fixture squashfs.img not generated"

    # squashfs mounting requires the squashfs kernel module in the Docker VM.
    # Skip gracefully when the module is unavailable.
    local probe_status=0
    docker run --rm --privileged \
        -v "${FIXTURES}/squashfs.img:/disk.img:ro" \
        -e "USB_PARTITION=2" \
        "${IMAGE}" run ls /mnt/part/etc/hostname >/dev/null 2>&1 \
        || probe_status=$?
    [[ "${probe_status}" -eq 0 ]] \
        || skip "squashfs kernel module unavailable in this Docker VM"

    run docker run --rm --privileged \
        -v "${FIXTURES}/squashfs.img:/disk.img:ro" \
        -e "USB_PARTITION=2" \
        "${IMAGE}" run cat /mnt/part/etc/hostname

    [ "${status}" -eq 0 ]
    [[ "${output}" == *"squashfs-test"* ]]
}

# ---------------------------------------------------------------------------
# btrfs.img (driver test)
# ---------------------------------------------------------------------------

@test "subcommand btrfs: btrfs partition is identified by info --json" {
    [[ -f "${FIXTURES}/btrfs.img" ]] || skip "fixture btrfs.img not generated"
    local fstype
    fstype=$(docker run --rm --privileged \
        -v "${FIXTURES}/btrfs.img:/disk.img:ro" \
        "${IMAGE}" info --json | \
        docker run --rm -i --entrypoint=jq \
            "${IMAGE}" -r '.partitions[] | select(.number == 2) | .fstype')
    [ "${fstype}" = "btrfs" ]
}

@test "subcommand btrfs: can read hostname from btrfs partition" {
    [[ -f "${FIXTURES}/btrfs.img" ]] || skip "fixture btrfs.img not generated"

    # Skip when /etc/hostname was not planted (generator skips the mount step
    # when the btrfs kernel module is unavailable in the generation container).
    local probe_status=0
    docker run --rm --privileged \
        -v "${FIXTURES}/btrfs.img:/disk.img:ro" \
        -e "USB_PARTITION=2" \
        "${IMAGE}" run ls /mnt/part/etc/hostname >/dev/null 2>&1 \
        || probe_status=$?
    [[ "${probe_status}" -eq 0 ]] \
        || skip "btrfs fixture has no /etc/hostname (generator skipped mount step)"

    run docker run --rm --privileged \
        -v "${FIXTURES}/btrfs.img:/disk.img:ro" \
        -e "USB_PARTITION=2" \
        "${IMAGE}" run cat /mnt/part/etc/hostname

    [ "${status}" -eq 0 ]
    [[ "${output}" == *"btrfs-test"* ]]
}

@test "subcommand xfs: xfs partition is identified by info --json" {
    [[ -f "${FIXTURES}/xfs.img" ]] || skip "fixture xfs.img not generated"
    local fstype
    fstype=$(docker run --rm --privileged \
        -v "${FIXTURES}/xfs.img:/disk.img:ro" \
        "${IMAGE}" info --json | \
        docker run --rm -i --entrypoint=jq \
            "${IMAGE}" -r '.partitions[] | select(.number == 2) | .fstype')
    [ "${fstype}" = "xfs" ]
}

@test "subcommand xfs: can read hostname from xfs partition" {
    [[ -f "${FIXTURES}/xfs.img" ]] || skip "fixture xfs.img not generated"

    # Skip when /etc/hostname was not planted in the fixture (the generator
    # skips the mount/write step when the xfs module is unavailable there).
    local probe_status=0
    docker run --rm --privileged \
        -v "${FIXTURES}/xfs.img:/disk.img:ro" \
        -e "USB_PARTITION=2" \
        "${IMAGE}" run ls /mnt/part/etc/hostname >/dev/null 2>&1 \
        || probe_status=$?
    [[ "${probe_status}" -eq 0 ]] \
        || skip "xfs fixture has no /etc/hostname (generator skipped mount step)"

    run docker run --rm --privileged \
        -v "${FIXTURES}/xfs.img:/disk.img:ro" \
        -e "USB_PARTITION=2" \
        "${IMAGE}" run cat /mnt/part/etc/hostname

    [ "${status}" -eq 0 ]
    [[ "${output}" == *"xfs-test"* ]]
}

# ---------------------------------------------------------------------------
# raw.img
# ---------------------------------------------------------------------------

# ---------------------------------------------------------------------------
# erofs.img (driver test)
# ---------------------------------------------------------------------------

@test "subcommand erofs: erofs partition is identified by info --json" {
    [[ -f "${FIXTURES}/erofs.img" ]] || skip "fixture erofs.img not generated"
    local fstype
    fstype=$(docker run --rm --privileged \
        -v "${FIXTURES}/erofs.img:/disk.img:ro" \
        "${IMAGE}" info --json | \
        docker run --rm -i --entrypoint=jq \
            "${IMAGE}" -r '.partitions[] | select(.number == 2) | .fstype')
    [ "${fstype}" = "erofs" ]
}

@test "subcommand erofs: can read hostname from erofs partition" {
    [[ -f "${FIXTURES}/erofs.img" ]] || skip "fixture erofs.img not generated"

    # erofs mounting requires the erofs kernel module in the Docker VM.
    # Skip gracefully when the module is unavailable.
    local probe_status=0
    docker run --rm --privileged \
        -v "${FIXTURES}/erofs.img:/disk.img:ro" \
        -e "USB_PARTITION=2" \
        "${IMAGE}" run ls /mnt/part/etc/hostname >/dev/null 2>&1 \
        || probe_status=$?
    [[ "${probe_status}" -eq 0 ]] \
        || skip "erofs kernel module unavailable in this Docker VM"

    run docker run --rm --privileged \
        -v "${FIXTURES}/erofs.img:/disk.img:ro" \
        -e "USB_PARTITION=2" \
        "${IMAGE}" run cat /mnt/part/etc/hostname

    [ "${status}" -eq 0 ]
    [[ "${output}" == *"erofs-test"* ]]
}

# ---------------------------------------------------------------------------
# raw.img
# ---------------------------------------------------------------------------

# ---------------------------------------------------------------------------
# lvm.img (layer driver test)
# ---------------------------------------------------------------------------

@test "subcommand lvm: can read hostname from LVM logical volume" {
    [[ -f "${FIXTURES}/lvm.img" ]] || skip "fixture not generated"
    docker run --rm --privileged "${IMAGE}" \
        bash -c 'vgscan 2>&1' >/dev/null 2>&1 \
        || skip "LVM/device-mapper unavailable in this Docker environment"
    run docker run --rm --privileged \
        -v "${FIXTURES}/lvm.img:/disk.img:ro" \
        -e "USB_PARTITION=1" \
        "${IMAGE}" run cat /mnt/part/etc/hostname
    [ "${status}" -eq 0 ]
    [[ "${output}" == *"lvm-test"* ]]
}

@test "subcommand lvm: invalid --lv does not poison the next run" {
    [[ -f "${FIXTURES}/lvm.img" ]] || skip "fixture not generated"
    docker run --rm --privileged "${IMAGE}" \
        bash -c 'vgscan 2>&1' >/dev/null 2>&1 \
        || skip "LVM/device-mapper unavailable in this Docker environment"

    run docker run --rm --privileged \
        -v "${FIXTURES}/lvm.img:/disk.img:ro" \
        -e "USB_PARTITION=1" \
        -e "USB_EXPLORE_LV=does-not-exist" \
        "${IMAGE}" run cat /mnt/part/etc/hostname
    [ "${status}" -ne 0 ]

    run docker run --rm --privileged \
        -v "${FIXTURES}/lvm.img:/disk.img:ro" \
        -e "USB_PARTITION=1" \
        "${IMAGE}" run cat /mnt/part/etc/hostname
    [ "${status}" -eq 0 ]
    [[ "${output}" == *"lvm-test"* ]]
}

# ---------------------------------------------------------------------------
# luks.img (layer driver test)
# ---------------------------------------------------------------------------

@test "subcommand luks: can read hostname from LUKS-encrypted partition" {
    [[ -f "${FIXTURES}/luks.img" ]] || skip "fixture not generated"
    run docker run --rm --privileged \
        -v "${FIXTURES}/luks.img:/disk.img:ro" \
        -e "USB_PARTITION=1" \
        -e "USB_EXPLORE_LUKS_PASSPHRASE=test-passphrase" \
        "${IMAGE}" run cat /mnt/part/etc/hostname
    [ "${status}" -eq 0 ]
    [[ "${output}" == *"luks-test"* ]]
}

@test "subcommand luks: can read hostname via passphrase file" {
    [[ -f "${FIXTURES}/luks.img" ]] || skip "fixture not generated"
    local ppfile="${TMPDIR_WORK}/luks-pp"
    printf 'test-passphrase' > "${ppfile}"
    run docker run --rm --privileged \
        -v "${FIXTURES}/luks.img:/disk.img:ro" \
        -e "USB_PARTITION=1" \
        -v "${ppfile}:/run/luks-passphrase:ro" \
        -e "USB_EXPLORE_LUKS_PASSPHRASE_FILE=/run/luks-passphrase" \
        "${IMAGE}" run cat /mnt/part/etc/hostname
    [ "${status}" -eq 0 ]
    [[ "${output}" == *"luks-test"* ]]
}

@test "subcommand luks: wrong passphrase exits non-zero" {
    [[ -f "${FIXTURES}/luks.img" ]] || skip "fixture not generated"
    run docker run --rm --privileged \
        -v "${FIXTURES}/luks.img:/disk.img:ro" \
        -e "USB_PARTITION=1" \
        -e "USB_EXPLORE_LUKS_PASSPHRASE=wrong-passphrase" \
        "${IMAGE}" run cat /mnt/part/etc/hostname
    [ "${status}" -ne 0 ]
}

@test "subcommand luks: no credentials exits non-zero with helpful message" {
    [[ -f "${FIXTURES}/luks.img" ]] || skip "fixture not generated"
    run docker run --rm --privileged \
        -v "${FIXTURES}/luks.img:/disk.img:ro" \
        -e "USB_PARTITION=1" \
        "${IMAGE}" run cat /mnt/part/etc/hostname
    [ "${status}" -ne 0 ]
    [[ "${output}" == *"no credentials"* ]]
}

# ---------------------------------------------------------------------------
# luks-lvm.img (stacking test: LUKS → LVM → ext4)
# ---------------------------------------------------------------------------

@test "subcommand luks-lvm: can read hostname through LUKS+LVM stack" {
    [[ -f "${FIXTURES}/luks-lvm.img" ]] || skip "fixture not generated"
    docker run --rm --privileged "${IMAGE}" \
        bash -c 'vgscan 2>&1' >/dev/null 2>&1 \
        || skip "LVM/device-mapper unavailable in this Docker environment"
    run docker run --rm --privileged \
        -v "${FIXTURES}/luks-lvm.img:/disk.img:ro" \
        -e "USB_PARTITION=1" \
        -e "USB_EXPLORE_LUKS_PASSPHRASE=test-passphrase" \
        "${IMAGE}" run cat /mnt/part/etc/hostname
    [ "${status}" -eq 0 ]
    [[ "${output}" == *"luks-lvm-test"* ]]
}

# ---------------------------------------------------------------------------
# LUKS format coverage: luks.img is LUKS2, showcase-enterprise is LUKS1
# ---------------------------------------------------------------------------

@test "subcommand luks: LUKS2 format (luks.img) mounts correctly" {
    [[ -f "${FIXTURES}/luks.img" ]] || skip "fixture not generated"
    run docker run --rm --privileged \
        -v "${FIXTURES}/luks.img:/disk.img:ro" \
        -e "USB_PARTITION=1" \
        --entrypoint bash \
        "${IMAGE}" -c '
            LP=$(losetup --find --show --read-only \
                --offset=1048576 --sizelimit=$((307200*512)) /disk.img)
            ver=$(cryptsetup luksDump "${LP}" 2>/dev/null \
                  | awk "/^Version:/{print \$2}")
            losetup -d "${LP}"
            echo "luks-version=${ver}"'
    [ "${status}" -eq 0 ]
    [[ "${output}" == *"luks-version=2"* ]]
}

@test "subcommand luks: LUKS1 format (showcase-enterprise) mounts correctly" {
    ensure_enterprise_fixture \
        || skip "could not generate showcase-enterprise.img"
    docker run --rm --privileged "${IMAGE}" \
        bash -c 'vgscan 2>&1' >/dev/null 2>&1 \
        || skip "LVM/device-mapper unavailable in this Docker environment"
    run docker run --rm --privileged \
        -v "${FIXTURES}/showcase-enterprise.img:/disk.img:ro" \
        -e "USB_PARTITION=2" \
        -e "USB_EXPLORE_LUKS_PASSPHRASE=showcase" \
        -e "USB_EXPLORE_LV=root" \
        "${IMAGE}" run cat /mnt/part/etc/hostname
    [ "${status}" -eq 0 ]
    [[ "${output}" == *"prod-db-01"* ]]
}

# ---------------------------------------------------------------------------
# Committed showcase fixture provenance
# ---------------------------------------------------------------------------

@test "fixture: committed showcase-home.img.gz matches pinned sha256" {
    [[ -f "${FIXTURES}/showcase-home.img.gz" ]] \
        || skip "showcase-home.img.gz not committed"
    [[ -f "${FIXTURES}/showcase-home.img.gz.sha256" ]] \
        || skip "no pinned checksum file"
    local expected actual
    expected=$(awk '{print $1}' "${FIXTURES}/showcase-home.img.gz.sha256")
    actual=$(sha256sum "${FIXTURES}/showcase-home.img.gz" | awk '{print $1}')
    [ "${actual}" = "${expected}" ]
}

# ---------------------------------------------------------------------------
# raw.img
# ---------------------------------------------------------------------------

# ---------------------------------------------------------------------------
# mount-server (SMB share)
# ---------------------------------------------------------------------------

@test "subcommand mount-server: smbd starts and partition is mounted" {
    [[ -f "${FIXTURES}/single-ext4.img" ]] || skip "fixture not generated"

    local port=19445
    MOUNT_CID=$(docker run --rm -d --privileged \
        -v "${FIXTURES}/single-ext4.img:/disk.img:ro" \
        -e "USB_PARTITION=2" \
        -p "${port}:${port}" \
        "${IMAGE}" mount-server "${port}" "test-share")

    # Wait for smbd to accept TCP connections
    local ready=false
    for _ in $(seq 1 20); do
        sleep 0.5
        if docker exec "${MOUNT_CID}" \
            bash -c "echo > /dev/tcp/localhost/${port}" 2>/dev/null; then
            ready=true; break
        fi
    done
    [[ "${ready}" == true ]] || skip "SMB server did not start within 10 s"

    # Verify partition is mounted and accessible
    run docker exec "${MOUNT_CID}" cat /mnt/part/etc/hostname
    [ "${status}" -eq 0 ]
    [[ "${output}" == *"usb-explore-test"* ]]
}

@test "subcommand mount-server: partition files are visible via smbd" {
    [[ -f "${FIXTURES}/single-ext4.img" ]] || skip "fixture not generated"

    local port=19446
    MOUNT_CID=$(docker run --rm -d --privileged \
        -v "${FIXTURES}/single-ext4.img:/disk.img:ro" \
        -e "USB_PARTITION=2" \
        -p "${port}:${port}" \
        "${IMAGE}" mount-server "${port}" "test-share")

    local ready=false
    for _ in $(seq 1 20); do
        sleep 0.5
        if docker exec "${MOUNT_CID}" \
            bash -c "echo > /dev/tcp/localhost/${port}" 2>/dev/null; then
            ready=true; break
        fi
    done
    [[ "${ready}" == true ]] || skip "SMB server did not start within 10 s"

    # Verify smbd is serving the correct share path by checking that
    # the smb.conf references /mnt/part and the share name
    run docker exec "${MOUNT_CID}" cat /tmp/smb.conf
    [ "${status}" -eq 0 ]
    [[ "${output}" == *"/mnt/part"* ]]
    [[ "${output}" == *"test-share"* ]]
    [[ "${output}" == *"read only = yes"* ]]
}

@test "subcommand mount-server: two concurrent sessions on different ports" {
    [[ -f "${FIXTURES}/single-ext4.img" ]] || skip "fixture not generated"

    local port1=19448 port2=19449

    MOUNT_CID=$(docker run --rm -d --privileged \
        -v "${FIXTURES}/single-ext4.img:/disk.img:ro" \
        -e "USB_PARTITION=2" \
        -p "${port1}:${port1}" \
        "${IMAGE}" mount-server "${port1}" "share-a")

    local cid2
    cid2=$(docker run --rm -d --privileged \
        -v "${FIXTURES}/single-ext4.img:/disk.img:ro" \
        -e "USB_PARTITION=2" \
        -p "${port2}:${port2}" \
        "${IMAGE}" mount-server "${port2}" "share-b")

    # Wait for both
    local ready1=false ready2=false
    for _ in $(seq 1 20); do
        sleep 0.5
        if [[ "${ready1}" == false ]]; then
            docker exec "${MOUNT_CID}" \
                bash -c "echo > /dev/tcp/localhost/${port1}" 2>/dev/null \
                && ready1=true
        fi
        if [[ "${ready2}" == false ]]; then
            docker exec "${cid2}" \
                bash -c "echo > /dev/tcp/localhost/${port2}" 2>/dev/null \
                && ready2=true
        fi
        [[ "${ready1}" == true && "${ready2}" == true ]] && break
    done
    [[ "${ready1}" == true && "${ready2}" == true ]] \
        || { docker stop "${cid2}" >/dev/null 2>&1 || true
             skip "concurrent SMB servers did not start within 10 s"; }

    # Both accessible
    run docker exec "${MOUNT_CID}" cat /mnt/part/etc/hostname
    [ "${status}" -eq 0 ]
    [[ "${output}" == *"usb-explore-test"* ]]

    run docker exec "${cid2}" cat /mnt/part/etc/hostname
    [ "${status}" -eq 0 ]
    [[ "${output}" == *"usb-explore-test"* ]]

    docker stop "${cid2}" >/dev/null 2>&1 || true
}

@test "subcommand mount-server: container stops cleanly on docker stop" {
    [[ -f "${FIXTURES}/single-ext4.img" ]] || skip "fixture not generated"

    local port=19447
    MOUNT_CID=$(docker run --rm -d --privileged \
        -v "${FIXTURES}/single-ext4.img:/disk.img:ro" \
        -e "USB_PARTITION=2" \
        -p "${port}:${port}" \
        "${IMAGE}" mount-server "${port}" "test-share")

    local ready=false
    for _ in $(seq 1 20); do
        sleep 0.5
        if docker exec "${MOUNT_CID}" \
            bash -c "echo > /dev/tcp/localhost/${port}" 2>/dev/null; then
            ready=true; break
        fi
    done
    [[ "${ready}" == true ]] || skip "SMB server did not start within 10 s"

    # Stop should succeed cleanly (smbd handles SIGTERM)
    run docker stop --time 5 "${MOUNT_CID}"
    [ "${status}" -eq 0 ]
    MOUNT_CID=""
}

# ---------------------------------------------------------------------------
# raw.img
# ---------------------------------------------------------------------------

@test "subcommand info --json: raw.img partition 2 raw_hint is non-null" {
    [[ -f "${FIXTURES}/raw.img" ]] || skip "fixture raw.img not generated"
    local hint
    hint=$(docker run --rm --privileged \
        -v "${FIXTURES}/raw.img:/disk.img:ro" \
        "${IMAGE}" info --json \
        | docker run --rm -i --entrypoint=jq "${IMAGE}" -r \
            '.partitions[] | select(.number == 2) | .raw_hint')
    [[ "${hint}" != "null" ]]
    [[ "${hint}" == *"BOOT_A_LEFT"* ]]
}
